/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import main.springApplication.RobotApplication;
import org.junit.Test;

import static org.junit.Assert.*;

public class MainTest {
    @Test
    public final void test() {
        final RobotApplication robotApplication = new RobotApplication();
    }
}
